name: demo
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  equatable: ^2.0.5
  http: ^1.2.1
  json_serializable: ^6.8.0
  shelf_cors_headers: ^0.1.5
  postgres: ^2.3.2
  process_run: ^0.14.2
  vm_service: ^14.2.1

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  flutter_test:
    sdk: flutter
